if(STATIC_ANALYSIS)
  find_program(CLANG_TIDY clang-tidy)
  if(CLANG_TIDY)
    set(CMAKE_CXX_CLANG_TIDY clang-tidy)
    message("Found clang-tidy!")
  else()
    message(WARNING "clang-tidy not found!")
  endif()
endif()
